const A='assets/';
const missions={1:['M1q1(8).png','M1q2(7).png','M1q3(7).png','M1q4(7).png','M1q5(7).png','M1q6(7).png','Z M1 conclusion(5).png'],2:['M2q1(7).png','m2q2(7).png','m2q3(7).png','m2q4(7).png','m2q5(6).png','m2q6(6).png','m2q7(6).png','m2z(5).png'],3:['m3q1(5).png','m3q2(5).png','m3q3(5).png','m3q4(5).png','m3q5(5).png','m3q6(5).png','m3q7(5).png','m3q8(4).png'],4:['m4q1(5).png','m4q2(5).png','m4q3(5).png','m4q4(5).png','m4q5(5).png','m4q6(2).png']};
const intros=['intro 1(4).png','intro 2(4).png','intro 3(4).png'];let state={screen:'intro',i:0,m:0};const app=document.querySelector('#app');
function shell(){app.innerHTML='<div class="app"><main class="phone" id="phone"></main></div>';return document.querySelector('#phone')}
function key(){return `m${state.m}p${state.i}`} function save(k,v){localStorage.setItem(k,v)} function load(k){return localStorage.getItem(k)||''}
function intro(){let p=shell();p.innerHTML=`<img class="pageimg" src="${A+intros[state.i]}"><button class="tapnext" aria-label="Continue"></button>`;p.querySelector('.tapnext').onclick=()=>{state.i++;state.i<intros.length?intro():select()}}
function select(){let p=shell();p.innerHTML=`<section class="selection"><div class="brand"><img src="${A}0a36501e-3dea-42de-970c-929ae221cd3b.png"> <span>TIMKEN MUSEUM OF ART</span></div><div class="title"><span class=a>Be a </span><span class=b>Secret </span><span class=c>Art </span><span class=e>Agent</span></div><div class="subtitle">Choose one of four missions, explore the galleries, and complete kid-friendly art detective challenges. Your answers stay on this device while you explore.</div><div class="grid">${[['1','Books, stories, landscapes & observation'],['2','Portraits, imagination, drawing & color'],['3','Books, portraits, colors & visual clues'],['4','Color, games, landscapes & drawing']].map(x=>`<div class="card m${x[0]}"><button class="cardmain" data-m="${x[0]}"><div class=num>${x[0]}</div><h2>Mission ${x[0]}</h2><p>${x[1]}</p><div class=choose>Choose mission →</div><i class=dot></i></button><button class="reset" data-r="${x[0]}">↻ Reset mission</button></div>`).join('')}</div></section>`;p.querySelectorAll('.cardmain').forEach(b=>b.onclick=()=>{state={screen:'mission',m:+b.dataset.m,i:0};renderMission()});p.querySelectorAll('.reset').forEach(b=>b.onclick=()=>{if(confirm(`Reset all saved answers for Mission ${b.dataset.r}?`)){Object.keys(localStorage).filter(k=>k.startsWith(`m${b.dataset.r}p`)).forEach(k=>localStorage.removeItem(k));b.textContent='✓ Reset';setTimeout(()=>b.textContent='↻ Reset mission',900)}})}
function renderMission(){let p=shell(),pages=missions[state.m],file=pages[state.i],last=state.i===pages.length-1;p.innerHTML=`<img class="pageimg" src="${A+file}"><button class="homebtn">⌂ Missions</button><div id="interact"></div><div class="nav"><button id="back">← Back</button><button id="next">${last?'Finish':'Next →'}</button></div>`;p.querySelector('.homebtn').onclick=select;p.querySelector('#back').onclick=()=>{if(state.i>0){state.i--;renderMission()}else select()};p.querySelector('#next').onclick=()=>{if(last){confetti(p);setTimeout(select,900)}else{state.i++;renderMission()}};addInteraction(p);if(last)confetti(p)}
function ta(box,k,style,ph='Tap here to type…',cls=''){box.insertAdjacentHTML('beforeend',`<textarea class="overlay textinput ${cls}" style="${style}" placeholder="${ph}">${load(k)}</textarea>`);let e=box.lastElementChild;e.oninput=()=>save(k,e.value)}
function draw(box,k,style){box.insertAdjacentHTML('beforeend',`<canvas class="overlay draw" style="${style}"></canvas><div class="drawtools"><button data-mode="draw">✎ Draw</button><button data-mode="erase">⌫ Erase</button><button data-mode="clear">Clear</button><button class="colorpick" data-color="#ef3d4d" style="background:#ef3d4d"></button><button class="colorpick" data-color="#3975c5" style="background:#3975c5"></button><button class="colorpick" data-color="#2db9ad" style="background:#2db9ad"></button><button class="colorpick" data-color="#222222" style="background:#222222"></button></div>`);setupCanvas(box.querySelector('canvas'),box.querySelector('.drawtools'),k)}
function hotspots(box,k,items,cls='hotspot'){let saved=JSON.parse(load(k)||'[]');items.forEach((s,n)=>{box.insertAdjacentHTML('beforeend',`<button class="overlay ${cls} ${saved.includes(n)?'selected':''}" data-n="${n}" style="${s}"></button>`)});box.querySelectorAll('.'+cls).forEach(b=>b.onclick=()=>{b.classList.toggle('selected');let vals=[...box.querySelectorAll('.'+cls+'.selected')].map(x=>+x.dataset.n);save(k,JSON.stringify(vals))})}
function addInteraction(p){const box=p.querySelector('#interact'),m=state.m,i=state.i,k=key();
if(m===1&&i===0)ta(box,k,'left:19%;top:57%;width:62%;height:9%');
if(m===1&&i===1){ta(box,k+'a','left:9%;top:64%;width:38%;height:9%','','speech');ta(box,k+'b','left:53%;top:64%;width:38%;height:9%','','speech')}
if(m===1&&i===2)ta(box,k,'left:13%;top:57%;width:74%;height:10%');
if(m===1&&i===3)draw(box,k,'left:13%;top:53%;width:74%;height:29%');
if(m===1&&i===4){let opts=['Narrative (tells a story)','Portrait (shows a person)','Landscape (shows the outdoors)','Still Life (shows things)'];let v=load(k);box.insertAdjacentHTML('beforeend',`<div class="mcwrap">${opts.map((x,n)=>`<button data-v="${n}" class="${v==n?'selected':''}">${x}</button>`).join('')}</div>`);box.querySelectorAll('.mcwrap button').forEach(b=>b.onclick=()=>{box.querySelectorAll('.mcwrap button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');save(k,b.dataset.v)})}
if(m===1&&i===5)ta(box,k,'left:10%;top:58%;width:80%;height:13%');
if(m===2&&i===0)ta(box,k,'left:10%;top:67%;width:80%;height:9%');
if(m===2&&i===1)draw(box,k,'left:30%;top:31%;width:44%;height:36%');
if(m===2&&i===2)ta(box,k,'left:10%;top:57%;width:80%;height:11%');
if(m===2&&i===3)hotspots(box,k,['left:30%;top:45%;width:7%;height:4%','left:30%;top:49.8%;width:7%;height:4%','left:30%;top:54.5%;width:7%;height:4%'],'radiohot');
if(m===2&&i===4)dragCircles(box,k,2,'coral');
if(m===2&&i===5)ta(box,k,'left:55%;top:45%;width:36%;height:9%');
if(m===2&&i===6)ta(box,k,'left:8%;top:18.5%;width:84%;height:5%');
if(m===3&&i===0)ta(box,k,'left:9%;top:56%;width:82%;height:10%');
if(m===3&&i===1)ta(box,k,'left:48%;top:47%;width:43%;height:12%');
if(m===3&&i===2)dragCircles(box,k,3,'teal');
if(m===3&&i===3)ta(box,k,'left:43%;top:38%;width:42%;height:13%');
if(m===3&&i===4)draw(box,k,'left:21%;top:48%;width:61%;height:42%');
if(m===3&&i===5)ta(box,k,'left:8%;top:50%;width:55%;height:12%');
if(m===3&&i===6)hotspots(box,k,['left:30.5%;top:41%;width:8%;height:4%','left:30.5%;top:46.5%;width:8%;height:4%','left:30.5%;top:52%;width:8%;height:4%','left:30.5%;top:57.5%;width:8%;height:4%'],'checkboxhot');
if(m===4&&i===0)ta(box,k,'left:8%;top:72%;width:84%;height:9%');
if(m===4&&i===1)ta(box,k,'left:8%;top:52%;width:84%;height:11%');
if(m===4&&i===2)ta(box,k,'left:8%;top:33%;width:39%;height:13%');
if(m===4&&i===3)ta(box,k,'left:64%;top:50%;width:28%;height:13%');
if(m===4&&i===4)draw(box,k,'left:50%;top:17%;width:43%;height:31%');
}

function dragCircles(box,k,count,tone){let saved=JSON.parse(load(k)||'null')||[];for(let n=0;n<count;n++){let el=document.createElement('div');el.className='dragcircle '+(tone==='teal'?'teal':'');let pos=saved[n]||{x:18+n*25,y:84};el.style.left=pos.x+'%';el.style.top=pos.y+'%';box.appendChild(el);let active=false,dx=0,dy=0;el.onpointerdown=e=>{active=true;el.setPointerCapture(e.pointerId);let r=el.getBoundingClientRect();dx=e.clientX-r.left;dy=e.clientY-r.top};el.onpointermove=e=>{if(!active)return;let r=box.parentElement.getBoundingClientRect();let x=Math.max(0,Math.min(r.width-el.offsetWidth,e.clientX-r.left-dx));let y=Math.max(0,Math.min(r.height-el.offsetHeight,e.clientY-r.top-dy));el.style.left=x/r.width*100+'%';el.style.top=y/r.height*100+'%'};el.onpointerup=()=>{active=false;saved[n]={x:parseFloat(el.style.left),y:parseFloat(el.style.top)};save(k,JSON.stringify(saved))}}}
function setupCanvas(c,tools,k){let ctx=c.getContext('2d'),drawing=false,last=null,mode='draw',color='#ef3d4d',saved=load(k);function size(){let r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);ctx.lineWidth=5;ctx.lineCap='round';ctx.strokeStyle=color;if(saved){let im=new Image;im.onload=()=>ctx.drawImage(im,0,0,r.width,r.height);im.src=saved}}setTimeout(size,0);function pt(e){let r=c.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top]}function start(e){drawing=true;last=pt(e);e.preventDefault()}function move(e){if(!drawing)return;let q=pt(e);ctx.globalCompositeOperation=mode==='erase'?'destination-out':'source-over';ctx.strokeStyle=color;ctx.lineWidth=mode==='erase'?22:5;ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(...q);ctx.stroke();last=q;e.preventDefault()}function end(){if(drawing){drawing=false;save(k,c.toDataURL())}}c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);window.addEventListener('pointerup',end);tools.querySelector('[data-mode=draw]').onclick=()=>mode='draw';tools.querySelector('[data-mode=erase]').onclick=()=>mode='erase';tools.querySelector('[data-mode=clear]').onclick=()=>{ctx.clearRect(0,0,c.width,c.height);localStorage.removeItem(k)};tools.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{color=b.dataset.color;mode='draw'})}
function confetti(p){for(let i=0;i<55;i++){let d=document.createElement('i');d.className='confetti';d.style.left=Math.random()*100+'%';d.style.background=['#2db9ad','#3975c5','#65be3f','#ef5b61','#ff9c19'][i%5];d.style.setProperty('--dx',(Math.random()*180-90)+'px');d.style.animationDelay=Math.random()*.5+'s';p.appendChild(d)}}intro();
